export const CELL_DEFAULT = 'CELL_DEFAULT';
export const CELL_HIGHLIGHTED = 'CELL_HIGHLIGHTED';
export const CELL_PICK_PLAYER = 'CELL_PICK_PLAYER';
export const CELL_PICK_COMPUTER = 'CELL_PICK_COMPUTER';